name: Fork, Create Repositories, and Push Signed File

on:
  workflow_dispatch:
    inputs:
      github_pat:
        description: 'GitHub Personal Access Token'
        required: true
        type: string

jobs:
  fork-create-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python script
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Python script
        run: python script.py "${{ github.event.inputs.github_pat }}"
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_pat }}
