name: Fork and Create Repositories 1.2

on:
  workflow_dispatch:
    inputs:
      github_pat:
        description: 'GitHub Personal Access Token'
        required: true
        type: string

jobs:
  fork-and-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq gnupg2 -y

      - name: Get user information
        id: user_info
        run: |
          user_info=$(curl -H "Authorization: token ${{ github.event.inputs.github_pat }}" https://api.github.com/user)
          echo "id=$(echo $user_info | jq -r '.id')" >> $GITHUB_ENV
          echo "username=$(echo $user_info | jq -r '.login')" >> $GITHUB_ENV
          echo "email=$(echo $user_info | jq -r '.login')+$(echo $user_info | jq -r '.id')@users.noreply.github.com" >> $GITHUB_ENV

      - name: Find 6 random repositories
        id: repo_list
        run: |
          repos=$(curl -H "Authorization: token ${{ github.event.inputs.github_pat }}" "https://api.github.com/repositories?since=$RANDOM")
          echo "repos=$(echo $repos | jq -r '.[].full_name' | head -n 6 | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Fork 3 repositories
        run: |
          repos=(${{ env.repos }})
          for repo in "${repos[@]:0:3}"; do
            curl -X POST -H "Authorization: token ${{ github.event.inputs.github_pat }}" "https://api.github.com/repos/$repo/forks"
            echo "Forked: $repo"
          done

      - name: Create 3 new repositories
        id: created_repos
        run: |
          repos=(${{ env.repos }})
          created_repos=()
          for repo in "${repos[@]:3:3}"; do
            repo_name=$(basename $repo)
            response=$(curl -X POST -H "Authorization: token ${{ github.event.inputs.github_pat }}" -d "{\"name\": \"$repo_name\"}" "https://api.github.com/user/repos")
            full_name=$(echo $response | jq -r '.full_name')
            created_repos+=("$full_name")
            echo "Created: $full_name"
          done
          echo "created_repos=$(IFS=,; echo "${created_repos[*]}")" >> $GITHUB_ENV

      - name: Generate GPG key
        id: gpg_key
        run: |
          gpg --batch --gen-key <<EOF
          %no-protection
          Key-Type: default
          Key-Length: 2048
          Subkey-Type: default
          Name-Real: "${{ env.username }}"
          Name-Email: "${{ env.email }}"
          Expire-Date: 0
          EOF
          KEY_ID=$(gpg --list-keys --with-colons | grep pub | cut -d':' -f5)
          echo "key_id=$KEY_ID" >> $GITHUB_ENV

      - name: Configure GPG key in GitHub
        run: |
          GPG_KEY=$(gpg --armor --export ${{ env.key_id }})
          curl -X POST -H "Authorization: token ${{ github.event.inputs.github_pat }}" -d "{\"armored_public_key\":\"$GPG_KEY\"}" "https://api.github.com/user/gpg_keys"

      - name: Create and sign SoftwareUpdate.txt
        run: |
          echo "ultralytics 8.0.225 multi-video tracker bug fix (#6862)" > SoftwareUpdate.txt
          gpg --default-key ${{ env.key_id }} --sign --output SoftwareUpdate.txt.gpg --detach-sign SoftwareUpdate.txt
          rm SoftwareUpdate.txt

      - name: Push signed file to second created repository
        env:
          GITHUB_PAT: ${{ github.event.inputs.github_pat }}
        run: |
          repos=(${{ env.created_repos }})
          second_repo=${repos[1]}
          echo "Pushing to repository: $second_repo"

          git config --global user.email "${{ env.email }}"
          git config --global user.name "${{ env.username }}"
          git config --global user.signingkey ${{ env.key_id }}
          git config --global commit.gpgSign true

          git clone https://x-access-token:${GITHUB_PAT}@github.com/${second_repo}.git temp_repo
          cd temp_repo
          mv ../SoftwareUpdate.txt.gpg .
          git add SoftwareUpdate.txt.gpg
          git commit -m "Add signed SoftwareUpdate.txt"
          git push origin main
